name: "elrond"
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+47

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  clipboard: ^0.1.3
  url_launcher: ^6.3.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  talker_flutter: ^4.4.1
  google_fonts: ^6.2.1
  share_plus: ^10.0.2  
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  bip39: ^1.0.6
  convert: ^3.1.0
  dio: ^5.4.3
  ed25519_hd_key: ^2.2.1
  freezed_annotation: ^2.4.0
  lints: ^4.0.0
  meta: ^1.15.0
  pinenacl: ^0.5.1
  pointycastle: ^3.9.0
  retrofit: ^4.1.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  http: ^1.2.2
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12 
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  retrofit_generator: ^7.0.8
  test: ^1.25.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/code/